name: Infrastructure Policy as Code Gatekeeper

# 1. The Triggers
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 2. The Jobs
jobs:
  security-scan:
    name: Checkov Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Checkov against Infrastructure
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform/
          # Fix for Warning 2: Added the "s" to the end of "dirs"
          external_checks_dirs: policies/
          framework: terraform
          soft_fail: false
